### ISSUE TITLE
Unable to spawn/add police car to garage

### ISSUE THREAD

**Issue by HondoE3** [Project-Phoenix-FiveM/ProjectPhoenix#17]
It's not possible to add police cars into the police garage, same as ambulance.

**Comment by SalazarXV** [comment]
[resources/[qb]/qb-ambulancejob/config.lua](https://github.com/Project-Phoenix-FiveM/ProjectPhoenix/blob/main/resources/%5Bqb%5D/qb-ambulancejob/config.lua) : line 97 - 119

[resources/[qb]/qb-policejob/config.lua](https://github.com/Project-Phoenix-FiveM/ProjectPhoenix/blob/main/resources/%5Bqb%5D/qb-policejob/config.lua) : line 105 - 162

If your vehicles are modded, try atleast to spawn them with the admin command : `/car ID`
