### ISSUE TITLE
improvement options

### ISSUE THREAD

**Issue by metaljanra** [Project-Phoenix-FiveM/ProjectPhoenix#9]
cdn fuel 

may be a more logical option. it creates extra space for users and keeps them busy. (job etc.)
https://github.com/CodineDev/cdn-fuel

renzu_shops

https://github.com/renzuzu/renzu_shops
https://github.com/renzuzu/qb-inventory (for example)

it's definitely a logical option. its integration is detailed.
there is qb integration. it has the interface.
I would say it adds 4 more different professions.
(business administration, truck driver, employer, hot dog carts (can be edited and used as an ice cream maker, etc.))
(it works more compatible with ox inventory)

**Comment by Rhodiniium** [comment]
Make sure to fully read Change-Log before making suggestions, cdn-fuel is already implented :) 

As for the shop's I wont be adding third party main resources, If you want to add it yourself you can :)
